"use client";

import { useCallback, useEffect, useState } from "react";
import Shell from "./Shell";
import { ArrowUpRight, CalendarDays, CheckCircle2, Clock3, Users, type LucideIcon } from "lucide-react";
import { Appointment, displayDate, displayTime, loadAppointments } from "../lib/appointments";

type Stat = [string, string, LucideIcon];
const statusLabel = (status: string) => status.charAt(0).toUpperCase() + status.slice(1);
const today = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };

export default function Dashboard() {
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refresh = useCallback(async () => { setLoading(true); try { setAppointments(await loadAppointments()); setError(""); } catch (cause) { setError(`Could not load dashboard data: ${cause instanceof Error ? cause.message : "Please try again."}`); } finally { setLoading(false); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const currentDay = today(); const active = appointments.filter((appointment) => !["cancelled", "completed"].includes(appointment.status)); const todays = active.filter((appointment) => appointment.date === currentDay); const upcoming = active.filter((appointment) => appointment.date >= currentDay).slice(0, 5);
  const stats: Stat[] = [["Today's Appointments", String(todays.length), CalendarDays], ["Upcoming Appointments", String(active.filter((appointment) => appointment.date >= currentDay).length), Clock3], ["Confirmed", String(appointments.filter((appointment) => appointment.status === "confirmed").length), Users], ["Completed", String(appointments.filter((appointment) => appointment.status === "completed").length), CheckCircle2]];
  return <Shell title="Dashboard" subtitle="A clear view of today's leads and appointments."><div className="stats">{stats.map(([label, value, Icon]) => <div className="stat" key={label}><span><Icon /></span><div><small>{label}</small><h2>{loading ? "—" : value}</h2><em>Live <i>appointment data</i></em></div></div>)}</div>{error && <p className="availability-message" role="alert">{error}</p>}<div className="cols"><div className="panel"><div className="head"><div><h3>Today's Appointments</h3><small>{displayDate(currentDay)}</small></div><a href="/appointments">View all <ArrowUpRight size={14} /></a></div>{loading ? <div className="empty">Loading appointments...</div> : todays.length === 0 ? <div className="empty">No appointments scheduled for today.</div> : todays.map((appointment) => <div className="row" key={appointment.id}><time>{displayTime(appointment.time)}</time><div className="person"><strong>{appointment.customerName}</strong><small>{appointment.service} · {appointment.location}</small></div><b className={`badge ${appointment.status}`}>{statusLabel(appointment.status)}</b></div>)}</div><div className="panel"><div className="head"><div><h3>Appointment status</h3><small>Current appointment totals</small></div><a href="/appointments">View all</a></div>{loading ? <div className="empty">Loading status totals...</div> : ["pending", "confirmed", "completed", "cancelled"].map((status) => <div className="lead" key={status}><strong>{statusLabel(status)[0]}</strong><div><b>{statusLabel(status)}</b><small>Appointments with this status</small></div><span>{appointments.filter((appointment) => appointment.status === status).length}</span></div>)}</div></div><div className="panel"><div className="head"><div><h3>Upcoming Appointments</h3><small>Next scheduled service calls</small></div></div><div className="table"><div className="tr upcoming-tr th"><b>Customer</b><b>Service</b><b>Date</b><b>Time</b><b>Status</b></div>{loading ? <div className="empty">Loading appointments...</div> : upcoming.length === 0 ? <div className="empty">No upcoming appointments.</div> : upcoming.map((appointment) => <div className="tr upcoming-tr" key={appointment.id}><span>{appointment.customerName}</span><span>{appointment.service}</span><span>{displayDate(appointment.date)}</span><span>{displayTime(appointment.time)}</span><span className={`badge ${appointment.status}`}>{statusLabel(appointment.status)}</span></div>)}</div></div></Shell>;
}
